spring.application.name=restaurant-service
server.port=9013

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true

# kafka
spring.kafka.bootstrap-servers=localhost:9092
# producer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# consumer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# JSON trusted package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.common.kafka.event

# topics
kafka.topics.order-created.name=order-created
kafka.topics.order-created.group-id=order-created-group
kafka.topics.order-created.concurrency=3

kafka.topics.payment-completed.name=payment-completed
kafka.topics.payment-completed.group-id=payment-completed-group
kafka.topics.payment-completed.concurrency=3

kafka.topics.payment-failed.name=payment-failed
kafka.topics.payment-failed.group-id=payment-failed-order-group
kafka.topics.payment-failed.concurrency=3

kafka.topics.restaurant-approved.name=restaurant-approved
kafka.topics.restaurant-approved.group-id=restaurant-approved-order-group
kafka.topics.restaurant-approved.concurrency=3