spring.application.name=restaurant-service
server.port=9013


spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true