spring.application.name=payment-service
server.port=9012

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true

# kafka
spring.kafka.bootstrap-servers=localhost:9092
# producer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# consumer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# JSON trusted package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.common.kafka.event


# topics
kafka.topics.order-created.name=order-created
kafka.topics.order-created.group-id=order-created-group
kafka.topics.order-created.concurrency=3
